# OUTPUT_LANG_INDEX start from 0
generator-localization-admin:
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=3 SPREADSHEET_ID=1kXQV3lueGP65mGfp00diYHjB_109oBW2RYhK-bcAf-8 GID_ID=lc-bot OUTPUT_FOLDER=../src/i18n/locales/en/defaults.json
	node localization/LocalizationGenerator.js OUTPUT_LANG_INDEX=4 SPREADSHEET_ID=1kXQV3lueGP65mGfp00diYHjB_109oBW2RYhK-bcAf-8 GID_ID=lc-bot OUTPUT_FOLDER=../src/i18n/locales/ja/defaults.json